'use strict';

// tests for getOrders
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getOrders', '/handler.js', 'getOrders');

describe('getOrders', () => {
  before((done) => {
    done();
  });

  it('Should return 200 if user has orders', async () => {
    const response = await wrapped.run({
      pathParameters: {
        user_id: "1"
      }
    });
    expect(response).to.not.be.empty;
    expect(response.body).to.not.be.empty;
    expect(response.statusCode).to.be.eql(200);
  });

  it('Should return 200 has no orders', async () => {
    const response = await wrapped.run({
      pathParameters: {
        user_id: "2"
      }
    });
    expect(response).to.not.be.empty;
    expect(response.body).to.be.eql('[]');
    expect(response.statusCode).to.be.eql(200);
  });
});
